### PR TITLE
Stop swifttracker thread

### PR DESCRIPTION
**Pull request by NielsZeilemaker**
SwiftTracker thread wasn't stopped if pymdht was

### CODE REVIEW

**Comment by rauljim** [comment]
Thanks for the patch.

**Comment by futtre** [comment]
Is there any class-level diagram (like a UML) of the whole repository?

/flutra

**Comment by rauljim** [comment]
No, but the code is designed in a way that almost everything is centralized in controller.py. So, you can see the most important interactions between modules if you walk through controller.py.

You can see a /kind of/ UML diagram by monitoring memory usage. I think we used Dowser.

/Raul

**Comment by futtre** [comment]
Yeah :)

was just wondering. After a few years, it becomes more difficult to
remember what class&functions were doing what :)

I guess a set of concentric (nested) circles help:
1. circle contains minitwisted & controller
2. responder, querier (and other modules: message, node, identifier, etc..)
3. routing_m & lookup_m modules

/flutra

**Pull request merged**
